name: Makefile CI

on:
  [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: make install

    - name: Lint with Pylint
      run: make lint

    - name: Test with Pytest
      run: make test
      
    - name: Format with Python black
      run: make format
